### ISSUE TITLE
Todo comment form is broken after installing the plugin

### ISSUE THREAD

**Issue by mupkoo** [evgeny-golubev/Safari-Extensions#3]
Hello,

after installing the plugin, adding new comment for a todo stops working.

This is without the plugin:
![screen shot 2014-05-12 at 9 27 40](https://cloud.githubusercontent.com/assets/1788571/2941272/d2b5e69c-d99e-11e3-9392-58d86875d7cb.png)

This is with the plugin enabled:
![screen shot 2014-05-12 at 9 27 19](https://cloud.githubusercontent.com/assets/1788571/2941274/dced3ffc-d99e-11e3-9776-c49df25d8665.png)

And I cannot add a new comment, because basecamp _cowardly refusing to save an empty comment_.

And here is the error that I get in the console
```
TypeError: 'undefined' is not a function (evaluating 'rangy.getSelection(this.doc.defaultView||this.doc.parentWindow)')
```
![screen shot 2014-05-12 at 9 41 21](https://cloud.githubusercontent.com/assets/1788571/2941328/7e8ba442-d9a0-11e3-91e8-05012b03c0c0.png)

PS version 1.6 does not have this problem.

**Comment by pjohnkeane** [comment]
Same here. Shame.
