### ISSUE TITLE
Comment Forms are broken with extension enabled

### ISSUE THREAD

**Issue by troutacular** [evgeny-golubev/Safari-Extensions#5]
Posting new messages in safari (Version 7.0.6 (9537.78.2) ) is not loading the wysiwig editor nor allowing a user to post a message in any comment form.

**Comment by colorful-tones** [comment]
Working great so far. And now Safari is my every day browser! Thank you, thank YOU!!

**Comment by evgeny-golubev** [comment]
@colorful-tones If you liked this extentions, you can donate to support it! This is the best way to say "thank you".
